services:
  minusx:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      mode: replicated
    restart: always
    env_file:
      .env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: minusx_user
      POSTGRES_PASSWORD: SpikyOP@123
      POSTGRES_DB: minusx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: